openapi: 3.0.2
info:
  title: Get a greeting
  description: If you ask for, I will greet you!
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /hello: # <- the path to be called; in our case ChatGPT will call http://localhost:3000/hello
    get: # <- the HTTP operation to perform on that path
      summary: ask for a greet
      description: |  # <- the "|" allowes us to write multiline description fields
        This Plugin geets you with a message.
      operationId: get_greetings
      responses:
        "200": # <- The HTTP Response Code (200 stands for OK)
          description: A successful response
          content:
            text/plain: # <- we just return a simple string
              schema:
                type: string
      security:
        - HTTPBearer: []
